
DROP TABLE IF EXISTS ip_addrs;
DROP SEQUENCE IF EXISTS ip_addr_id_seq;
DROP TABLE IF EXISTS mac_addrs;
DROP SEQUENCE IF EXISTS mac_addr_id_seq;
DROP TABLE IF EXISTS virtual_ports;
DROP SEQUENCE IF EXISTS virtual_port_id_seq;
DROP TABLE IF EXISTS wirings;
DROP SEQUENCE IF EXISTS wiring_id_seq;
DROP TABLE IF EXISTS vlans;
DROP SEQUENCE IF EXISTS vlan_id_seq;
DROP TABLE IF EXISTS ports;
DROP SEQUENCE IF EXISTS port_id_seq;
DROP TABLE IF EXISTS switches;
DROP SEQUENCE IF EXISTS switch_id_seq;
DROP TABLE IF EXISTS hosts;
DROP SEQUENCE IF EXISTS host_id_seq;
  
